[[rulesets]]
group = "ğŸŠ é»‘åå•"
ruleset = "orange/Clash/Blacklist.list"

[[rulesets]]
group = "ğŸŠ ç™½åå•"
ruleset = "orange/Clash/Whitelist.list"

[[rulesets]]
group = "ğŸ¬ Mdcx"
ruleset = "orange/Clash/Mdcx.list"

[[rulesets]]
group = "ğŸ¤– claude"
ruleset = "orange/Clash/Claude.list"